# Generated by Django 5.0.3 on 2024-04-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildobject',
            name='total_budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
