# Generated by Django 5.0.3 on 2024-06-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsa_app', '0002_alter_buildobject_total_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sh_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='tools_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools_sheet', to='tsa_app.toolssheet'),
        ),
    ]
